name: Publish

on:
  release:
    types: [published, edited]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.tag_name }}
      - name: Dependencies
        run: npm install && npm run build
      - name: Tag
        uses: JasonEtco/build-and-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
